### ISSUE TITLE
PDF output generates matplotlib error

### ISSUE THREAD

**Issue by simsong** [amueller/word_cloud#128]
I modified the constitution example to generate PDF output:

```
from os import path
from wordcloud import WordCloud

d = path.dirname(__file__)

# Read the whole text.                                                                                                                                                                         
text = open(path.join(d, 'constitution.txt')).read()

# Generate a word cloud image                                                                                                                                                                  
wordcloud = WordCloud().generate(text)

# Display the generated image:                                                                                                                                                                 
# the matplotlib way:                                                                                                                                                                          

# take relative word frequencies into account, lower max_font_size                                                                                                                             
wordcloud = WordCloud(max_font_size=40, relative_scaling=.5).generate(text)
if True:
    import matplotlib.pyplot as plt
    plt.figure(figsize=(12,12))
    plt.imshow(wordcloud)
    plt.axis("off")
    #plt.show()                                                                                                                                                                                
    plt.savefig("foo.pdf","pdf")

```      

And I get this error:
```
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PIL/ImageDraw.py:99: UserWarning: setfont() is deprecated. Please set the attribute directly instead.
  "Please set the attribute directly instead.")
Traceback (most recent call last):
  File "wc.py", line 30, in <module>
    plt.savefig("foo.pdf","pdf")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 688, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/figure.py", line 1565, in savefig
    self.canvas.print_figure(*args, **kwargs)
TypeError: print_figure() got multiple values for argument 'dpi'
```

**Comment by amueller** [comment]
that's because you gave "pdf" as the positional argument for "dpi". You don't have to specify the  format, just plt.savefit("foo.pdf") will do.

**Comment by simsong** [comment]
Ah, you are right. However, it seems that the PDF file is still a bitmap, not line art. Is there any way to fix that?


----

**Comment by amueller** [comment]
I think because the font rendering is done by PIL, there is unfortunately currently no way to generate vectorgraphics with wordcloud :-/

**Comment by amueller** [comment]
this project can btw: https://github.com/SalvaEB/mask_word_cloud
I should maybe switch to cairo, too, or bokeh, but I currently don't have the time to work on this.

**Comment by simsong** [comment]
Hm... Okay. I may look at the code to see if we could do the rendering with matplotlib....

**Comment by amueller** [comment]
You need to know the width and height of the rendered text. Maybe that can be computed in matplotlib.

**Comment by amueller** [comment]
I guess you could always render it and check the size...
