### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by a93ushakov** [amueller/word_cloud#150]
I try to install `word_cloud` in `docker` container, but I had failed.

```sh
FROM debian:testing
MAINTAINER Alex Ushakov <a93ushakov@gmail.com>

RUN \
  apt update && \
  apt install \
    -y \
      git \
      ca-certificates \
      python-pip \
      wget \
      unzip \
      g++ \
      libjpeg-dev \
      zlib1g-dev \
      python-dev

WORKDIR /tmp
RUN wget https://github.com/amueller/word_cloud/archive/master.zip
RUN unzip master.zip
RUN rm master.zip

WORKDIR word_cloud-master
RUN pip install -r requirements.txt
RUN pip install wordcloud
RUN apt install -y libfreetype6-dev libxft-dev  libjpeg62
RUN pip install pillow
```

Can someone to help?

Error is:
```
root@17cc19b0e55b:/tmp/word_cloud-master/examples# python simple.py 
Traceback (most recent call last):
  File "simple.py", line 17, in <module>
    wordcloud = WordCloud().generate(text)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 448, in generate
    return self.generate_from_text(text)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 434, in generate_from_text
    self.generate_from_frequencies(words)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 317, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 37, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```

In `ubuntu` base image - the same problem.

**Comment by a93ushakov** [comment]
And, yes, `pip install wordcloud` doesnt work.

**Comment by amueller** [comment]
Googling the error message finds the solution:
http://stackoverflow.com/questions/4011705/python-the-imagingft-c-module-is-not-installed

**Comment by a93ushakov** [comment]
```docker
FROM debian:testing
MAINTAINER Alex Ushakov <a93ushakov@gmail.com>

RUN \
  apt update && \
  apt install \
    -y \
      git \
      ca-certificates \
      python-pip \
      wget \
      unzip \
      g++ \
      libjpeg-dev \
      zlib1g-dev \
      python-dev \
      libfreetype6-dev \
      libxft-dev \
      libjpeg62

WORKDIR /tmp
RUN wget https://github.com/amueller/word_cloud/archive/master.zip
RUN unzip master.zip
RUN rm master.zip

WORKDIR word_cloud-master
RUN pip install -r requirements.txt
RUN pip install wordcloud
RUN pip install pillow
RUN pip install matplotlib
```

This builds ok, but no images exported.

**Comment by amueller** [comment]
what do you mean?

**Comment by a93ushakov** [comment]
In `examples` directory I had copied `simple.py and *.txt` to another directory and tried: `python simple.py`. As I understand it should generate an image in this directory, right?

**Comment by amueller** [comment]
No, it pops up a window. You can use the [to_file](http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud) method to write it to a file
