### ISSUE TITLE
ImportError: No module named 'PIL'

### ISSUE THREAD

**Issue by Santi871** [amueller/word_cloud#173]
This seems to stem from the fact PIL isn't available in Python 3.x and was succeeded by Pillow.

```
Traceback (most recent call last):
  File "E:\...\Python\wordcloud_test", line 9, in <module>
    from wordcloud import WordCloud
  File "C:\Python34\lib\site-packages\wordcloud\__init__.py", line 1, in <module>
    from .wordcloud import WordCloud, STOPWORDS, random_color_func, get_single_color_func
  File "C:\Python34\lib\site-packages\wordcloud\wordcloud.py", line 17, in <module>
    from PIL import Image
ImportError: No module named 'PIL'
```

simple.py running on Python 3.4.

**Comment by Santi871** [comment]
Solved by reinstalling Pillow. 'import PIL' statements still work with Pillow. Sorry for the mess here, first time using GitHub issues.

**Comment by amueller** [comment]
no worries, yes, installing pillow is the right solution :)
