### ISSUE TITLE
TypeError on CLI

### ISSUE THREAD

**Issue by michaelaye** [amueller/word_cloud#191]
(stable) └─❱❱❱ pdftotext active_co2_jets_aye.pdf - | wordcloud_cli.py --imagefile wordcloud2.png
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/stable/bin/wordcloud_cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('wordcloud==1.2.1', 'wordcloud_cli.py')
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/wordcloud-1.2.1-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/wordcloud_cli.py", line 83, in <module>
    main(parse_args(sys.argv[1:]))
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/wordcloud-1.2.1-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/wordcloud_cli.py", line 19, in main
    color_func=args.color_func, background_color=args.background_color).generate(args.text)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/wordcloud-1.2.1-py3.5-macosx-10.6-x86_64.egg/wordcloud/wordcloud.py", line 551, in generate
    return self.generate_from_text(text)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/wordcloud-1.2.1-py3.5-macosx-10.6-x86_64.egg/wordcloud/wordcloud.py", line 537, in generate_from_text
    self.generate_from_frequencies(words)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/wordcloud-1.2.1-py3.5-macosx-10.6-x86_64.egg/wordcloud/wordcloud.py", line 428, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
TypeError: integer argument expected, got float

This is using the current GH master on macOS 10.11.6.
I checked that it's not my setup, checking out v1.2.1 it worked. maybe missing a dependency?

**Comment by michaelaye** [comment]
not sure what happened, after doing a git bisect and several installs, it works. I started with a develop install, maybe that messed up something...
