### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cjmay** [amueller/word_cloud#240]
Running `wordcloud_cli.py` (from master) on sanitized data I was preparing for a separate issue raised an IndexError:

```
$ wordcloud_cli.py --text letters.txt --imagefile letters.png
Traceback (most recent call last):
  File "/home/hltcoe/cmay/.local/bin/wordcloud_cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('wordcloud==1.3', 'wordcloud_cli.py')
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/wordcloud-1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/wordcloud_cli.py", line 81, in <m$
dule>
    main(parse_args(sys.argv[1:]))
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/wordcloud-1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/wordcloud_cli.py", line 19, in ma$
n
    color_func=args.color_func, background_color=args.background_color).generate(args.text)
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/wordcloud-1.3-py2.7-linux-x86_64.egg/wordcloud/wordcloud.py", line 556, in generate
    return self.generate_from_text(text)
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/wordcloud-1.3-py2.7-linux-x86_64.egg/wordcloud/wordcloud.py", line 542, in generate_fro$
_text
    self.generate_from_frequencies(words)
  File "/home/hltcoe/cmay/.local/lib/python2.7/site-packages/wordcloud-1.3-py2.7-linux-x86_64.egg/wordcloud/wordcloud.py", line 353, in generate_fro$
_frequencies
    max_frequency = float(frequencies[0][1])
IndexError: list index out of range
$ cat letters.txt
a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f f g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h h i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j j k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k k l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l l m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m m n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n n o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p p q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q q r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t
```

**Comment by cjmay** [comment]
Looks like same as #201

**Comment by cjmay** [comment]
Reopened because #201 seems to be somewhat orthogonal to this issue: it would seem the words in this file are getting filtered out but it's not clear why.  Whatever is causing that, I think it would be nice to be able to optionally turn it off?

**Comment by amueller** [comment]
single letter words are ignored by the default regex. You can provide a different regex to keep them. If you like, I'd happily accept a PR that makes that more prominent in the docs.

**Comment by cjmay** [comment]
I added a justification for making this behavior optional in the PR: basically, in my setting we might have our own pre-processing routine we prefer, or are even constrained to use, and we sometimes want a word cloud that represents our (already pre-preprocessed) data as closely as possible.  The presence of short words in the word cloud could, for example, help point out a difference in self-reference (with "I") between two texts.  Or in a more engineering-oriented setting it could reveal an issue in the system that generated the text.

**Comment by amueller** [comment]
@cjmay I totally want to support your use-case. I think it would be best for that to use ``generate_from_frequencies``, though. There is additional heuristics in there for capitalization and removing trailing "s"s and some of them are already controlled by parameters, but I would rather not have individual parameters for all possible combinations. Using ``generate_from_frequencies`` allows you to do exactly the thing you want.
