### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by maoxiaobai** [amueller/word_cloud#258]
Traceback (most recent call last):
  File "/home/azkaban/svn/WordCloud/test.py", line 32, in <module>
    wc.generate(text)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 558, in generate
    return self.generate_from_text(text)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 544, in generate_from_text
    self.generate_from_frequencies(words)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 371, in generate_from_frequencies
    width = mask.shape[1]
IndexError: tuple index out of range

I couldn't run the demo correctly, the info is showed as the text.
Please help me. Thank you!

**Comment by amueller** [comment]
Sorry for the slow reply, I was traveling. What is the code that you are running? It looks like ``mask`` is a 1d array, when it needs to be 2d.

**Comment by maoxiaobai** [comment]
Thanks for your reply. I reinstalled the plugin, and the problem was solved. 
Wish you have a good holiday!
