### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by AlphaGoMK** [amueller/word_cloud#291]
When I use WordCloud.fit_word(), it shows AttributeError: 'list' object has no attribute 'items'.
It also doesn't work when I use WordCloud.generate_from_frequencies()
How to fix it?
Thanks :)
Code:
`frequencies = [(u'知乎',5),(u'小段同学',4),(u'曲小花',3),(u'中文分词',2),(u'样例',1)]`
`wordcloud = WordCloud().fit_words(frequencies)`
Error

> Traceback (most recent call last):
  File "D:/VS_Project/Python/WordCloudSample/WCSample.py", line 19, in <module>
    wordcloud = WordCloud().fit_words(frequencies)
  File "C:\Users\AlphaGoMK\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wordcloud\wordcloud.py", line 331, in fit_words
    return self.generate_from_frequencies(frequencies)
  File "C:\Users\AlphaGoMK\AppData\Local\Programs\Python\Python36-32\lib\site-packages\wordcloud\wordcloud.py", line 350, in generate_from_frequencies
    frequencies = sorted(frequencies.items(), key=item1, reverse=True)
AttributeError: 'list' object has no attribute 'items'

**Comment by amueller** [comment]
Never versions of wordcloud take a dictionary as input, not a list of tuples.

**Comment by cannycophp** [comment]
http://python.jobbole.com/88325/?utm_source=blog.jobbole.com&utm_medium=relatedPosts
修改版本，拷下来的不能用
