### ISSUE TITLE
Error when mask selected

### ISSUE THREAD

**Issue by RedNoo** [amueller/word_cloud#299]
Hello,
I am getting the following error when I added mask parameter. How can I fix this?
Best 
Onder

Ps: Windows 10

wordcloud_cli.py --text datarank.txt  --mask beautiful.jpg  --imagefile test.jpg
Traceback (most recent call last):
  File "C:\Users\onder\AppData\Local\Programs\Python\Python36-32\Scripts\wordcloud_cli.py", line 86, in <module>
    main(parse_args(sys.argv[1:]))
  File "C:\Users\onder\AppData\Local\Programs\Python\Python36-32\Scripts\wordcloud_cli.py", line 70, in parse_args
    args.mask = np.array(Image.open(args.mask))
  File "c:\users\onder\appdata\local\programs\python\python36-32\lib\site-packages\PIL\Image.py", line 2486, in open
    prefix = fp.read(16)
  File "c:\users\onder\appdata\local\programs\python\python36-32\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 251: character maps to <undefined>

**Comment by amueller** [comment]
It seems like something is wrong with the mask. it can't be read. Maybe try converting to png? or make sure it's actually in jpeg?

**Comment by RedNoo** [comment]
I don't know why but I am closing this issue. Maybe it's only my computers problem.

**Comment by amueller** [comment]
does it work now?
Have you tried converting it to png?

**Comment by RedNoo** [comment]
no didn't work, I will not use cli.

**Comment by amueller** [comment]
Did it work with the programmatic interface?

**Comment by RedNoo** [comment]
Yes, your example files worked.
