### ISSUE TITLE
Unicode words not detect by word cloud

### ISSUE THREAD

**Issue by sht-design** [amueller/word_cloud#303]
when we have unicode words in txt file i will get this error : 
Traceback (most recent call last):
  File "D:/Program Files (x86)/word_cloud-master/examples/a_new_hope.py", line 45, in <module>
    random_state=1).generate(text)
  File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 565, in generate
    return self.generate_from_text(text)
  File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 547, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 353, in generate_from_frequencies
    "got %d." % len(frequencies))
ValueError: We need at least 1 word to plot a word cloud, got 0.

That not detect unicode words like Arabic and etc
and when we add a English word that just show that word without any unicode word
i use python 2.7

**Comment by amueller** [comment]
This depends on your locale configuration and how it interacts with the regular expressions in python.
Check out the discussion on thai: #272

**Comment by amueller** [comment]
Maybe we should add something about that to the readme. If you figure arabic out, let me know!

**Comment by amueller** [comment]
Maybe also check out this issue: https://github.com/amueller/word_cloud/issues/70

**Comment by sht-design** [comment]
Hi again
thank you for your answer , i solved that problem with your guide :+1: 
i write for other users that have problem :
First must install this package : pip install git+https://github.com/mpcabd/python-arabic-reshaper
and this package : https://github.com/MeirKriheli/python-bidi
then must import this two line where other packages imported : 
```
from arabic_reshaper import arabic_reshaper
from bidi.algorithm import get_display
```
then must set utf-8 for texts : 
`text = text.decode("utf-8")
text = arabic_reshaper.reshape(text)
text = get_display(arabic_reshaper.reshape(text))`

then you can get final result from your text :)
thank you again

**Comment by amueller** [comment]
Great. It would be nice if you could provide a pull request with an example in arabic. It's a common language and it seems a bit tricky to do.

**Comment by amueller** [comment]
Though it might be a bit easier with python 3? I'm not sure.

**Comment by chatlovely** [comment]
I test that on python 3 but alphabet was unreadable 
And also in python2&3 stop words not work with Arabic words

**Comment by amueller** [comment]
@chatlovely What do you mean by that? The built-in stop words are for English only. You should be able to provide different stopwords. If that's not working, please open a separate issue with a reproducible example.

**Comment by IsuruLiyanage** [comment]
I had a similar problem with Sinhala language. Supplying both regexp and text as Unicode worked for me.
`text = text.decode("utf-8")
cloud = WordCloud(font_path="kaputaunicode.ttf", regexp=ur"[a-zA-Zං-෴']+").generate(text)`

**Comment by slaronge** [comment]
Would this method work as well for emojis?

**Comment by amueller** [comment]
yes, if you set the regexp correctly. That might be a bit more tricky, as emojis are not usually separated by whitespace, though. But you can certainly come up with a regexp that separates them
