### ISSUE TITLE
generate_from_frequencies error:

### ISSUE THREAD

**Issue by sahase** [amueller/word_cloud#308]
Traceback (most recent call last):

  File "<ipython-input-4-189bc405589c>", line 1, in <module>
    runfile('/cs535/miniProject2/mp2prob4.py', wdir='/cs535/miniProject2')

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/cs535/miniProject2/mp2prob4.py", line 49, in <module>
    wc = WordCloud().generate_from_frequencies(dictPerYr[year])

  File "/anaconda3/lib/python3.6/site-packages/wordcloud-1.3.1-py3.6-macosx-10.9-x86_64.egg/wordcloud/wordcloud.py", line 422, in generate_from_frequencies
    + (1 - rs)) * font_size))

ValueError: cannot convert float NaN to integer
I was testing my code on a very small dataset when I got this error.
I have a hunch that it may be due to the frequencies for each year being very small.  And for some words the frequency being zero.  Do I need to eliminate zero frequencies from my dict before passing it to wordcloud functions?
Edit: I now suspect it may be a combination of having lots of zero values and/or having several equally weighted words, i.e.: a frequency table where all of the words appear either zero or one time. I don't think this will be a problem with most real world datasets.

**Comment by amueller** [comment]
can you provide code to reproduce? There was a similar issue in #307.

**Comment by amueller** [comment]
closing as no reply / no code to reproduce
