### ISSUE TITLE
ValueError when using "prism" colourmap

### ISSUE THREAD

**Issue by asongtoruin** [amueller/word_cloud#331]
#### Description
When using the `'prism'` colourmap from `matplotlib`, a `ValueError` can occur. This seems more common with larger text files.

#### Steps/Code to Reproduce
```
import wordcloud as wc

# get transcript info
with open('mobydick.txt', 'r') as f:
    transcript = f.read()

cloud = wc.WordCloud(max_words=30000,
                     min_font_size=1,
                     collocations=True,
                     colormap='prism')

cloud.generate(transcript)

cloud.to_file('test.png')
```
Using [mobydick.txt](https://github.com/amueller/word_cloud/files/1625878/mobydick.txt) (thanks to [Project Gutenberg](http://www.gutenberg.org/files/2701/2701-0.txt))

#### Actual Results
The following `ValueError`:
```
Traceback (most recent call last):
  File "C:/Users/asongtoruin/cmap tester.py", line 17, in <module>
    cloud.to_file('test.png')
  File "C:\Anaconda3\envs\temp\lib\site-packages\wordcloud\wordcloud.py", line 650, in to_file
    img = self.to_image()
  File "C:\Anaconda3\envs\temp\lib\site-packages\wordcloud\wordcloud.py", line 592, in to_image
    draw.text(pos, word, fill=color, font=transposed_font)
  File "C:\Anaconda3\envs\temp\lib\site-packages\PIL\ImageDraw.py", line 210, in text
    ink, fill = self._getink(fill)
  File "C:\Anaconda3\envs\temp\lib\site-packages\PIL\ImageDraw.py", line 106, in _getink
    ink = ImageColor.getcolor(ink, self.mode)
  File "C:\Anaconda3\envs\temp\lib\site-packages\PIL\ImageColor.py", line 128, in getcolor
    color, alpha = getrgb(color), 255
  File "C:\Anaconda3\envs\temp\lib\site-packages\PIL\ImageColor.py", line 113, in getrgb
    raise ValueError("unknown color specifier: %r" % color)
ValueError: unknown color specifier: 'rgb(255, 0, -0)'
```

#### Versions
Windows-7-6.1.7601-SP1
Python 3.5.4 |Anaconda, Inc.| (default, Nov  8 2017, 14:34:30) [MSC v.1900 64 bit (AMD64)]
NumPy 1.13.3
matplotlib 2.1.0
wordcloud 1.3.2

**Comment by amueller** [comment]
thanks for the report. should be fixed in master.

**Comment by Himanshu-idexcel** [comment]
How to handle a value error ,if we passing a wrong color name ? i am not able to handle this error

**Comment by amueller** [comment]
@Himanshu-idexcel can you please provide more detail and/or code to reproduce and the error message you're getting?
