### ISSUE TITLE
 No module named 'wordcloud.query_integral_image'

### ISSUE THREAD

**Issue by syahdeini** [amueller/word_cloud#357]
#### Description

Hi I got this when I try to import wordcloud
#### Actual Results

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bok/word_cloud-master/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "/home/bok/word_cloud-master/wordcloud/wordcloud.py", line 25, in <module>
    from .query_integral_image import query_integral_image
ModuleNotFoundError: No module named 'wordcloud.query_integral_image'

**Comment by amueller** [comment]
How did you install wordcloud?
