### ISSUE TITLE
i can't seem to run it on chinese words (corpus) 

### ISSUE THREAD

**Issue by ikelca** [amueller/word_cloud#360]
is this wordcloud py supporting chinese ? 
i tried to run on txt file containing chinese words, but gives error

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/wordcloud_cli.py", line 86, in <module>
    main(parse_args(sys.argv[1:]))
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/wordcloud_cli.py", line 70, in parse_args
    args.mask = np.array(Image.open(args.mask))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 2552, in open
    prefix = fp.read(16)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by amueller** [comment]
Have you checked this example:
https://github.com/amueller/word_cloud/blob/master/examples/wordcloud_cn.py
?

**Comment by ikelca** [comment]
thank you 
i tested with wordcloud_cn.py and it actually worked, but Im still confused about few parameters 
```
wc = WordCloud(font_path=font_path, background_color="white", max_words=2000, mask=back_coloring,
               max_font_size=100, **random_state**=42, width=1000, height=860, `margin`=2,)
```
what is random_state used for here? and how about margin? 

really appreciate your help !

**Comment by amueller** [comment]
random state is used to make sure the result are the same every time the code is run. margin changes the space around words. Both are explained in the docs.
