### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by hossein-pourbozorg** [amueller/word_cloud#371]
>>> import wordcloud
>>> import math
>>> wc = wordcloud.WordCloud()
>>> wc.generate_from_frequencies({'a': math.nan})
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    wc.generate_from_frequencies({'a': math.nan})
  File "/usr/local/lib/python3.6/dist-packages/wordcloud/wordcloud.py", line 431, in generate_from_frequencies
    + (1 - rs)) * font_size))
ValueError: cannot convert float NaN to integer
>>> wc.generate_from_frequencies({'a': math.inf})
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    wc.generate_from_frequencies({'a': math.inf})
  File "/usr/local/lib/python3.6/dist-packages/wordcloud/wordcloud.py", line 431, in generate_from_frequencies
    + (1 - rs)) * font_size))
ValueError: cannot convert float NaN to integer>>> import wordcloud
>>> import math
>>> wc = wordcloud.WordCloud()
>>> wc.generate_from_frequencies({'a': math.nan})
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    wc.generate_from_frequencies({'a': math.nan})
  File "/usr/local/lib/python3.6/dist-packages/wordcloud/wordcloud.py", line 431, in generate_from_frequencies
    + (1 - rs)) * font_size))
ValueError: cannot convert float NaN to integer
>>> wc.generate_from_frequencies({'a': math.inf})
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    wc.generate_from_frequencies({'a': math.inf})
  File "/usr/local/lib/python3.6/dist-packages/wordcloud/wordcloud.py", line 431, in generate_from_frequencies
    + (1 - rs)) * font_size))
ValueError: cannot convert float NaN to integer

**Comment by amueller** [comment]
Why should this work, and what should it do?

**Comment by hossein-pourbozorg** [comment]
if this shouldn't work.
i think, it's better to raise a more explicit error.
it seem like a bug to me at the first time.
