### ISSUE TITLE
cannot import name 'WordCloud'

### ISSUE THREAD

**Issue by javazsh** [amueller/word_cloud#377]
#### Description
I can run this code when I define a function in IDLE ,but I can't run it when I save it as a file In E 
#### Steps/Code to Reproduce

#wordcloud.py
import jieba
from wordcloud import WordCloud
txt =open('E:\\pythoncode\\sanguo.txt',encoding='utf-8').read()
wordList=jieba.lcut(txt)
txt=' '.join(wordList)
w=WordCloud(width=1000,height=700,max_words=20,font_path='msyh.ttc')
w.generate(txt)
w.to_file('E:\\wordcloud1.png')
#### Expected Results

create a new file wordcloud1.png
#### Actual Results

Traceback (most recent call last):
  File "E:/pythonCode/issue.py", line 4, in <module>
    from wordcloud import WordCloud
  File "E:/pythonCode\wordcloud.py", line 3, in <module>
    from wordcloud import WordCloud
ImportError: cannot import name 'WordCloud'
#### Versions

Windows-10-10.0.16299-SP0
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
NumPy 1.14.3
matplotlib 2.2.2
wordcoud 1.4.1

**Comment by amueller** [comment]
How do you run the file? You are likely to not be using the right Python environment. See http://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/ for some details.

**Comment by javazsh** [comment]
@amueller I run this file just by click Run->Run Module.I have seen that artical but I don't use Jupyter Notebook.And I still don't konw how to solve this problem.Whatever,Thank you  a lot

**Comment by scritrolf** [comment]
Could the problem have been that your python script file was also named wordcloud.py? I do this frequently, curse for 30m and remember that you just cannot name your script file like any import.

**Comment by Abdusalamstd** [comment]
"ImportError: cannot import name 'WordCloud' from 'wordcloud' "
I just have this problem. It seems personal python code file name cannot be "wordcloud.py" like this. 
Only change the file name just OK. Problem has soloved
