### ISSUE TITLE
Exception with unicode in stopwords using wordcloud_cli.py

### ISSUE THREAD

**Issue by mfortini** [amueller/word_cloud#379]
#### Description
Using unicode in stopwords leads to an exception using wordcloud_cli.py

#### Steps/Code to Reproduce
Using stopwords-it.txt from https://github.com/stopwords-iso/stopwords-it

```
$ wordcloud_cli.py --stopwords stopwords-it.txt --text text.txt --imagefile wc.png


```

#### Expected Results
No error is thrown

#### Actual Results
```
Traceback (most recent call last):
  File "/usr/local/bin/wordcloud_cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('wordcloud==1.4.1', 'wordcloud_cli.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud-1.4.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/wordcloud_cli.py", line 185, in <module>
    main(*parse_args(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/wordcloud-1.4.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/wordcloud_cli.py", line 164, in parse_args
    args['stopwords'] = set(map(str.strip, f.readlines()))
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

#### Versions
Linux-4.16.0-x86_64-with-debian-buster-sid
('Python', '2.7.15 (default, May  1 2018, 05:55:50) \n[GCC 7.3.0]')
('NumPy', '1.13.3')
('matplotlib', '2.1.1')
('wordcoud', '1.4.1')

**Comment by amueller** [comment]
Works on Python3 ;)

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — the specific traceback reported here is no longer reachable.

Evidence:
- The traceback came from CPython 2.7 hitting `TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'` against `set(map(str.strip, f.readlines()))`. The same CLI line now reads `set(map(lambda l: l.strip(), f.readlines()))` ([wordcloud/wordcloud_cli.py#L238-L240](https://github.com/amueller/word_cloud/blob/93c5e4cd50c5f2c56ec7eb624a620790dab5df6c/wordcloud/wordcloud_cli.py#L238-L240)) which works natively on Py3 `str` (which already is unicode).
- The project no longer supports Python 2 at all: `pyproject.toml` declares `requires-python = ">=3.9"` ([pyproject.toml#L10](https://github.com/amueller/word_cloud/blob/93c5e4cd50c5f2c56ec7eb624a620790dab5df6c/pyproject.toml#L10)), and `test.yml` runs CI against 3.9–3.14 only ([.github/workflows/test.yml](https://github.com/amueller/word_cloud/blob/93c5e4cd50c5f2c56ec7eb624a620790dab5df6c/.github/workflows/test.yml)). The Py2.7 install path that produced the original report can't be re-created against a current release.

If you've hit a Py3 unicode-in-stopwords bug with a *different* signature on a current `wordcloud` install, that'd be worth a fresh issue with a current traceback so it's not anchored to the Py2-era code path. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually against current `main`.*
