### ISSUE TITLE
Dependencies of wordcloud are hard to install!

### ISSUE THREAD

**Issue by mirjalil** [amueller/word_cloud#39]
I want to use wordcloud in ubuntu 12.04, but I put so much effort to install _imagingft and eventulally I installed it. Yet, when I try to run simple.py I got an error:

```
python simple.py 
/usr/local/lib/python2.7/dist-packages/PIL/Image.py:71: RuntimeWarning: The _imaging extension was built for another  version of Pillow or PIL
  warnings.warn(str(v), RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/PIL/Image.py:71: RuntimeWarning: The _imaging extension was built for another  version of Pillow or PIL
  warnings.warn(str(v), RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/PIL/Image.py:71: RuntimeWarning: The _imaging extension was built for another  version of Pillow or PIL
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "simple.py", line 10, in <module>
    from wordcloud import WordCloud
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import WordCloud, STOPWORDS, random_color_func
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 14, in <module>
    from PIL import Image
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 55, in <module>
    raise ImportError("The _imaging extension was built for another "
ImportError: The _imaging extension was built for another  version of Pillow or PIL
```

**Comment by danielquinn** [comment]
This may not solve the problem, but I thought it worth mentioning.

In the past, when I've had issues with PIL/Pillow, it was because the host OS's copy of this library was interfering with the one in my virtualenv.  The solution for this is to:

* Create a virtualenv if you haven't already
* Create an empty file called `sitecustomize.py` in `<virtualenv>/lib/python2.7/` (replace python2.7 with whatever python version you're using)
* Use `pip` to install whatever packages you need, including `Pillow`.
