### ISSUE TITLE
Why aren't we using NLTK Bigram Collocation Finder?

### ISSUE THREAD

**Issue by enfarose** [amueller/word_cloud#396]
I was wondering why we are computing collocation score on our own, while we could use the collocation score from the NLTK library for finding the likelihood?

**Comment by amueller** [comment]
Because I don't want to add a dependency on nltk, and I'm implementing
exactly the same. It's just a couple of lines of code. I think nltk also
has three word collocations which would be nice, but also not that hard to
add.

**Comment by enfarose** [comment]
Yes, that makes sense. I think I could work on adding three word
collocations.

**Comment by amueller** [comment]
Cool, go for it!

**Comment by amueller** [comment]
Readability can be greatly improved if you [format](https://help.github.com/articles/creating-and-highlighting-code-blocks/) your code snippets and complete error messages appropriately. For example:

    ```python
    print(something)
    ```
generates:
```python
print(something)
```
And:

    ```pytb
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'hello'
    ```
generates:
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'hello'
```
You can edit your issue descriptions and comments at any time to improve readability. This helps maintainers a lot. Thanks!

**Comment by amueller** [comment]
What kind of normalization did you have in mind?
