### ISSUE TITLE
cli: Add support for installing and running"wordcloud_cli" on all platforms

### ISSUE THREAD

**Issue by jcfr** [amueller/word_cloud#420]
#### Description

After installing wordcloud as an editable install, it is not possible to run the `wordcloud_cli.py` script available in the source tree.

#### Steps/Code to Reproduce

After installing wordcloud locally using:

```
pip install -e .
```

and then trying to run the CLI with:

```
$ python ./wordcloud/wordcloud_cli.py --text examples/constitution.txt   --imagefile consitution.png
```

It fails with 

```pytb
Traceback (most recent call last):
  File "./wordcloud/wordcloud_cli.py", line 15, in <module>
    import wordcloud as wc
  File "/home/jcfr/Projects/word_cloud/wordcloud/wordcloud.py", line 25, in <module>
    from .query_integral_image import query_integral_image
SystemError: Parent module '' not loaded, cannot perform relative import
```

Note that running the installed cli works:

```
$ wordcloud_cli.py --text examples/constitution.txt   --imagefile consitution.png
```

But this is unlikely to work on windows and prevent developer from improving the CLI without having to reinstall it after each update, or having to  copy the script our and back into the right folder.

**Comment by jcfr** [comment]
xref #353
