### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by jaraco** [amueller/word_cloud#445]
#### Description

Running wordcloud with simple input of "foo" results in TypeError.

#### Steps/Code to Reproduce

Using rwt to download and run wordcloud, I get a TypeError.

```
$ echo foo | rwt wordcloud -- -m wordcloud
Collecting wordcloud
  Using cached https://files.pythonhosted.org/packages/c7/07/e43a7094a58e602e85a09494d9b99e7b5d71ca4789852287386e21e74c33/wordcloud-1.5.0-cp37-cp37m-macosx_10_6_x86_64.whl
Collecting numpy>=1.6.1 (from wordcloud)
  Using cached https://files.pythonhosted.org/packages/a8/e1/838e35e6f44e2bc19bf902e945c34ae730a33a8e346d6208bf7c4d751416/numpy-1.15.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pillow (from wordcloud)
  Using cached https://files.pythonhosted.org/packages/99/c8/550f3416afe7b6726efc8a7f2249a38d6ae65c3514ef6c36bdc8485868b7/Pillow-5.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy, pillow, wordcloud
Successfully installed numpy-1.15.3 pillow-5.3.0 wordcloud-1.5.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-_9ebsdpk/wordcloud/__main__.py", line 37, in <module>
    main()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-_9ebsdpk/wordcloud/__main__.py", line 33, in main
    wordcloud_cli_main(*wordcloud_cli_parse_args(sys.argv[1:]))
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-_9ebsdpk/wordcloud/wordcloud_cli.py", line 93, in main
    image.save(imagefile, format='png', optimize=True)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-_9ebsdpk/PIL/Image.py", line 1969, in save
    save_handler(self, fp, filename)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-_9ebsdpk/PIL/PngImagePlugin.py", line 734, in _save
    fp.write(_MAGIC)
TypeError: write() argument must be str, not bytes
```

#### Expected Results

Image should be generated to stdout.

#### Versions

```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)
[Clang 6.0 (clang-600.0.57)]
```

(other versions downloaded above)

**Comment by jaraco** [comment]
Passing `--imagefile` bypasses the issue.

**Comment by amueller** [comment]
writing an image to stdout is not supported right now. PR welcome.

**Comment by guanzo** [comment]
Then the docs shouldn't say it can write the image to stdout..

![](https://i.gyazo.com/6e142c481083788eb3cfb4a7d0df6331.png)

**Comment by amueller** [comment]
@guanzo thanks, that's right. Do you want to sent a PR?

**Comment by guanzo** [comment]
Actually I am interested in a PR. I'm calling this lib's cli from node and it's been a huge hassle. This lib is awesome and I'd like to contribute. However, i'm a js guy and python is not my strength, although i'm comfortable with the basics.

Why is it a hassle?

1. multi language wordclouds

Whether or not it's an effective form of data visualization is irrelevant to me, I just think it looks cool. 

Problem is, now I need a multi lang stopword file. This lib only accepts 1 stopword file, so I've had to concenate multiple files into one, before passing to the lib. For example, if a wordcloud has english, spanish, german, i have to concenate `en.txt, es.txt, de.txt` into one file, then pass to the lib.

Ideally, this lib accepts multiple stopword fields. This is something i'm willing to PR.

2. Writing the image to stdout

What are the basic steps needed to achieve this? Is it just this?

```py
import sys
sys.stdout.buffer.write(b"some binary data")
```

**Comment by amueller** [comment]
Hey. So I would be happy to take a pr for 2, but probably not for 1. That's something that's fairly easy to do with command line tools. You can just use cat and a pipe or something like that, right?

And I have never tried to write an image to stdout, but I think that should do it. Do you have something that would consume that?

**Comment by amueller** [comment]
for the concat, I think doing ``--stopwords `cat en.txt es.txt de.txt` `` would do what you want.

**Comment by guanzo** [comment]
I have a node process that runs the wordcloud_cli as a child process. I'd like the child process to emit the image data to it's stdout, so that my node process can get the image, optimize it, and upload to S3. That's the ideal plan. Right now, I have to use the filesystem as a middleman and its super annoying.

I'll try the cmd line trick for #1 thanks.

**Comment by guanzo** [comment]
I don't think ``--stopwords `cat en.txt es.txt de.txt` `` works? 

The script will receive the contents of the `cat` command, and treat it as a filename.

**Comment by amueller** [comment]
Sorry, I  can't help with node. You're right about the cat command not working because ``--stopwords`` takes indeed a file. I'm not sure if there's an easy way to pass stopwords as a list on the command line and if it's a good idea to allow that.
I don't think it's a good idea to do this inside wordcloud, though. What is the issue with using the file system?

**Comment by guanzo** [comment]
> What is the issue with using the file system?

There's no real issue, it's just a minor annoyance. Ideally the node <-> python process communication is all done in memory, which is why I want this lib to write to stdout. Could you check out my PR btw?

**Comment by amueller** [comment]
The problem is that stdin is only one channel and so you can't really feed both stopwords and the text. Yeah I'll check out the other PR, thanks!
