### ISSUE TITLE
KeyError: 'foo' building simple word cloud with spaces in words

### ISSUE THREAD

**Issue by jaraco** [amueller/word_cloud#446]
#### Description

Attempting to build a word cloud from a file containing one phrase per line results in KeyError.

#### Steps/Code to Reproduce
```
$ echo 'Foo Bar\nFoo Bar\n' | rwt wordcloud -- -m wordcloud --imagefile authors.png --regexp '[ \w]+'
Collecting wordcloud
  Using cached https://files.pythonhosted.org/packages/c7/07/e43a7094a58e602e85a09494d9b99e7b5d71ca4789852287386e21e74c33/wordcloud-1.5.0-cp37-cp37m-macosx_10_6_x86_64.whl
Collecting numpy>=1.6.1 (from wordcloud)
  Using cached https://files.pythonhosted.org/packages/a8/e1/838e35e6f44e2bc19bf902e945c34ae730a33a8e346d6208bf7c4d751416/numpy-1.15.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pillow (from wordcloud)
  Using cached https://files.pythonhosted.org/packages/99/c8/550f3416afe7b6726efc8a7f2249a38d6ae65c3514ef6c36bdc8485868b7/Pillow-5.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy, pillow, wordcloud
Successfully installed numpy-1.15.3 pillow-5.3.0 wordcloud-1.5.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/__main__.py", line 37, in <module>
    main()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/__main__.py", line 33, in main
    wordcloud_cli_main(*wordcloud_cli_parse_args(sys.argv[1:]))
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/wordcloud_cli.py", line 89, in main
    wordcloud.generate(text)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/wordcloud.py", line 605, in generate
    return self.generate_from_text(text)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/wordcloud.py", line 586, in generate_from_text
    words = self.process_text(text)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/wordcloud.py", line 563, in process_text
    word_counts = unigrams_and_bigrams(words, self.normalize_plurals)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-21h77osc/wordcloud/tokenization.py", line 55, in unigrams_and_bigrams
    word1 = standard_form[bigram[0].lower()]
KeyError: 'foo'
```

#### Expected Results

A wordcloud should be generated with "Foo Bar" as the only phrase.

#### Versions

```
Darwin-18.0.0-x86_64-i386-64bit
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)
[Clang 6.0 (clang-600.0.57)]
```

Other versions appear above.

**Comment by jaraco** [comment]
This seems related, but distinct from #183.

Also, I'm unsure if I'm supplying the regex properly to match one phrase per line.

**Comment by amueller** [comment]
thanks for the report. Can you see if you can reproduce with the python interface? Though I expect it's an issue with the command line interface.

**Comment by amueller** [comment]
what's rwt?

**Comment by jaraco** [comment]
I really need to rename it to `pip-run` for searchability and a more intuitive name. [rwt is here](https://pypi.org/project/rwt). It uses pip to install packages on demand in a temporary environment.

**Comment by amueller** [comment]
can you provide an example to reproduce without using rwt?

**Comment by jaraco** [comment]
Sure, just create a virtualenv, run `pip install` with the same parameters as with rwt before `--`, then run python with whatever parameters after `--`, then delete your virtualenv (at your leisure).

**Comment by jaraco** [comment]
i.e. 

```
$ pip install wordcloud
$ echo "Foo Bar\nFoo Bar\n" | python -m wordcloud --imagefile authors.png --regexp '[ \w]+'
```

**Comment by amueller** [comment]
the executable is ``wordcloud_cli.py`` so this shouldn't (and doesn't) work.

**Comment by jaraco** [comment]
:/

Providing a [runpy](https://docs.python.org/3/library/runpy.html) entry point is really valuable, and making it a simple name like `wordcloud` is really convenient... especially when the `console_scripts` like `wordcloud_cli` aren't available. I'd say it _should_ be supported, and was pleased when I found out _it is_ ([ref](https://github.com/amueller/word_cloud/blob/master/wordcloud/__main__.py)).

**Comment by jaraco** [comment]
Regardless, the same issue occurs with the cli:

```
word_cloud master $ echo "Foo Bar\nFoo Bar\n" | env/bin/wordcloud_cli --imagefile authors.png --regexp '[ \w]+'
Traceback (most recent call last):
  File "env/bin/wordcloud_cli", line 11, in <module>
    sys.exit(main())
  File "/Users/jaraco/code/public/word_cloud/env/lib/python3.7/site-packages/wordcloud/__main__.py", line 33, in main
    wordcloud_cli_main(*wordcloud_cli_parse_args(sys.argv[1:]))
  File "/Users/jaraco/code/public/word_cloud/env/lib/python3.7/site-packages/wordcloud/wordcloud_cli.py", line 89, in main
    wordcloud.generate(text)
  File "/Users/jaraco/code/public/word_cloud/env/lib/python3.7/site-packages/wordcloud/wordcloud.py", line 605, in generate
    return self.generate_from_text(text)
  File "/Users/jaraco/code/public/word_cloud/env/lib/python3.7/site-packages/wordcloud/wordcloud.py", line 586, in generate_from_text
    words = self.process_text(text)
  File "/Users/jaraco/code/public/word_cloud/env/lib/python3.7/site-packages/wordcloud/wordcloud.py", line 563, in process_text
    word_counts = unigrams_and_bigrams(words, self.normalize_plurals)
  File "/Users/jaraco/code/public/word_cloud/env/lib/python3.7/site-packages/wordcloud/tokenization.py", line 55, in unigrams_and_bigrams
    word1 = standard_form[bigram[0].lower()]
KeyError: 'foo'
```

**Comment by amueller** [comment]
ok, I can reproduce. Basically the code detecting collocations doesn't make sense if you allow space in your regex. You can use "--no_collocations" but probably there should be a better error message.

**Comment by amueller** [comment]
So minimum example is
```python
from wordcloud import WordCloud
wc = WordCloud(regexp=r"[ \w]+")
wc.generate("Foo Bar\nFoo Bar\n")
```
and the issue is that in ``unigrams_and_bigrams`` I assume that you can go from bigram to unigram by splitting on whitespace. But your regex allows whitespace to be inside a token. I either need to detect that and disable the collocations feature in that case or rewrite the code so that it works with whitespace within tokens. A bigram would then be two lines in your example.

**Comment by jaraco** [comment]
By the way, the whole reason I'm wanting to get words from lines in a file is because I'm attempting to use the output from `git log --format=%an` to create a word cloud of authors in a git repo. How cool would that be?

**Comment by amueller** [comment]
pretty cool ;). yeah definitely disable collocations for that. it might be a bit more natural to actually directly compute counts in git and pass those to wordcloud. Though providing files with counts is not supported in the command line interface right now. PR welcome ;)

**Comment by amueller** [comment]
Pretty sure you mangled @jcfr's name though ;) It's "Jean-Christophe Fillion-Robin"

**Comment by jcfr** [comment]
I confirm :)

**Comment by jaraco** [comment]
Regex probably needs to include `-`. I'll retry. Yes, that's better.

`git -C ~/p/word_cloud log --format=%an | python -m pip-run -q wordcloud -- -m wordcloud --imagefile authors.png --regexp r'[ \w\.\-]+' --no_collocations`

![authors](https://user-images.githubusercontent.com/308610/48032122-730b6900-e124-11e8-9cf2-577cccc56798.png)

**Comment by lastessa** [comment]
how can i use --no_collocation inside python code
example: wc = WordCloud(max_words=1000, mask=mask, regexp=normal_word, no_collocations=False,
               random_state=1).generate(text)

not work

**Comment by amueller** [comment]
@lastessa Have you looked at the docstring? it's ``collocations=False``.
