### ISSUE TITLE
 'ImageDraw' object has no attribute 'setfont'

### ISSUE THREAD

**Issue by lixiaofengCH** [amueller/word_cloud#447]
#### Actual Results

Traceback (most recent call last):
  File "D:/pharm_install_repository/workspace/tfdemo/com/synway/examples/tokenizess.py", line 43, in <module>
    wc = WordCloud().generate(a)
  File "C:\Users\Administrator\venv\lib\site-packages\wordcloud\wordcloud.py", line 417, in generate
    return self.generate_from_text(text)
  File "C:\Users\Administrator\venv\lib\site-packages\wordcloud\wordcloud.py", line 403, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Users\Administrator\venv\lib\site-packages\wordcloud\wordcloud.py", line 295, in generate_from_frequencies
    draw.setfont(transposed_font)
AttributeError: 'ImageDraw' object has no attribute 'setfont'

**Comment by lixiaofengCH** [comment]
code below:

--------------------------------------------------------
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
from wordcloud import WordCloud
a = 'this is a wordcloud show test'
wc = WordCloud().generate(a)
wc.to_file('wc.jpg')
plt.imshow(wc)
plt.axis('off')
plt.savefig('plt.png')

**Comment by amueller** [comment]
what versions of pil and wordcloud do you have installed?

**Comment by amueller** [comment]
closing as no reply
