### ISSUE TITLE
`fonttools` missing from the dependency

### ISSUE THREAD

**Issue by wakita** [amueller/word_cloud#521]
#### Description
`fonttools` missing from the dependency

#### Steps/Code to Reproduce

Add the following to `examples/masked.py` and execute.
```
with open(path.join(d, 'alice.svg'), 'w') as w:
    w.write(wc.to_svg())
```

#### Expected Results
No error is thrown; `examples/alice.svg` should be created.

#### Actual Results

```
Traceback (most recent call last):
  File "masked.py", line 39, in <module>
    wc.to_svg(path.join(d, "alice.svg"))
  File "/Users/wakita/.venvs/hakone_wc/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 836, in to_svg
    import fontTools
ModuleNotFoundError: No module named 'fontTools'
```

#### Versions
Latest

**Comment by amueller** [comment]
It's a soft dependency. It's not needed for most of the library so it seems overkill to make it a dependency.
