### ISSUE TITLE
running example masked word cloud error

### ISSUE THREAD

**Issue by gaoxuesong** [amueller/word_cloud#56]
root@xsubuntu2:~/word_cloud/examples# python masked.py
Traceback (most recent call last):
  File "masked.py", line 27, in <module>
    wc.generate(text)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 313, in generate
    self.fit_words(self.words_)
  File "/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py", line 180, in fit_words
    font = ImageFont.truetype(self.font_path, font_size)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 240, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 137, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource

My OS is Ubuntu 1204
Please help me solve the problem, thanks.

**Comment by gaoxuesong** [comment]
set FONT_PATH on Ubuntu 12.04
add FONT_PATH=/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf in /etc/profile
