### ISSUE TITLE
Can't turn application into .exe despite adding 'stopwords'

### ISSUE THREAD

**Issue by JRitmeester** [amueller/word_cloud#565]
I tried multiple times to package my application using Wordcloud into a one-fille executable using
`pyinstaller --hidden-import=pkg_resources.py2_warn --onefile --add-data="_<path>_\venv\Lib\site-packages\wordcloud\stopwords;." _<path>_\venv\main.py`

But the error persists:
```MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File " _<path>_\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "gui.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File " _<path>_\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\wordcloud\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File " _<path>_\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\wordcloud\wordcloud.py", line 35, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '<AppData>\\Local\\Temp\\_MEI60682\\wordcloud\\stopwords'
[4352] Failed to execute script main
```
Any ideas would be great!

**Comment by amueller** [comment]
You need to add the stopword file to the bundle:
https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle

**Comment by JRitmeester** [comment]
Thanks. I read that before but I have no idea what they mean with supplying it to the Analysis call. I thought adding it like this would do the trick, but I guess not...

**Comment by amueller** [comment]
This seems to be a pyinstaller question, not a wordcloud question. But at a glance it looks like you have a semicolon after ``stopwords`` where there should be a colon?

**Comment by JRitmeester** [comment]
Yes, I'll look elsewhere. But no, semicolon seems to be required on Windows, since that is the OS delimiter, rather than a colon, which is for other OSes. It wouldnt run with a colon, but it does run with a semi-colon.

**Comment by amueller** [comment]
is it in the right folder? Might need to be ``wordcloud`` instead of ``.``? Is the stopword file in ``<AppData>\\Local\\Temp\\_MEI60682\``  or anywhere in that folder?

**Comment by JRitmeester** [comment]
No, it is not. I have used the absolute path to <project_folder>\venv\Lib\site-packages\wordcloud\stopwords, but it doesn't make a difference.
