### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by setegonz** [amueller/word_cloud#633]
#### Description
The example code from the wordcloud [website ](https://amueller.github.io/word_cloud/auto_examples/single_word.html#sphx-glr-download-auto-examples-single-word-py) throws an error. I know the problem is not the code but I have not been able to find what is causing me the problem.

#### Code to Reproduce
```
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud

text = "square"

x, y = np.ogrid[:300, :300]

mask = (x - 150) ** 2 + (y - 150) ** 2 > 130 ** 2
mask = 255 * mask.astype(int)


wc = WordCloud(background_color="white", repeat=True, mask=mask)
wc.generate(text)

plt.axis("off")
plt.imshow(wc, interpolation="bilinear")
plt.show()
```

#### Expected Results
![image](https://user-images.githubusercontent.com/11341688/115428548-7ef22500-a1d0-11eb-874a-296ccf040337.png)

#### Actual Results
`TypeError: expected string or bytes-like object`

#### Versions
```
Windows-10-10.0.19041-SP0
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
NumPy 1.19.2
matplotlib 3.3.4
wordcoud 1.8.1
```

**Comment by setegonz** [comment]
@amueller Thanks for having a look at this!
```
Traceback (most recent call last):

  File "<ipython-input-1-44315c2f8917>", line 14, in <module>
    wc.generate(text)

  File "C:\Users\Steven\anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 632, in generate
    return self.generate_from_text(text)

  File "C:\Users\Steven\anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 614, in generate_from_text
    self.generate_from_frequencies(words)

  File "C:\Users\Steven\anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 496, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 853, in truetype
    return freetype(font)

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 173, in __init__
    freetype_version = parse_version(features.version_module("freetype2"))

  File "C:\Users\Steven\anaconda3\lib\site-packages\packaging\version.py", line 57, in parse
    return Version(version)

  File "C:\Users\Steven\anaconda3\lib\site-packages\packaging\version.py", line 296, in __init__
    match = self._regex.search(version)

TypeError: expected string or bytes-like object
```

**Comment by amueller** [comment]
Looks like it's an issue with ``PIL``, what version are you using? Maybe try upgrading (or even downgrading)?

**Comment by setegonz** [comment]
`Image.PILLOW_VERSION 8.2.0`

**Comment by setegonz** [comment]
Following this question https://stackoverflow.com/questions/49060525/install-jupyterlab-in-pip3-throws-typeerror-expected-string-or-bytes-like-obje/51163568#51163568

I did the following:

* Opened file "C:\Users\Name\anaconda3\Lib\site-packages\packaging\version.py"

* Changed the code on line 297 from `match = self._regex.search(version)` to `match = self._regex.search(str(version))`

* Re-ran the initial code

which shows:

```
Traceback (most recent call last):

  File "<ipython-input-95-4b5feeafbaab>", line 14, in <module>
    wc.generate(text)

  File "C:\Users\Steven\anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 632, in generate
    return self.generate_from_text(text)

  File "C:\Users\Steven\anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 614, in generate_from_text
    self.generate_from_frequencies(words)

  File "C:\Users\Steven\anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 496, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 853, in truetype
    return freetype(font)

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 185, in __init__
    if core.HAVE_RAQM:

  File "C:\Users\Steven\anaconda3\lib\site-packages\PIL\ImageFont.py", line 44, in __getattr__
    raise ImportError("The _imagingft C module is not installed")

ImportError: The _imagingft C module is not installed
```

Can you think of any additional information that may help me?

**Comment by amueller** [comment]
I would try not to edit the system files, that might get you in trouble later.
I think this might be relevant:
https://stackoverflow.com/a/57258342/676634

remove PIL, make sure all folders and egg files are gone, and then maybe install pillow again using conda?

**Comment by njk639** [comment]
Getting the same error as well here with PIL/Wordcloud installed via Conda:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-df16413ec1be> in <module>
      8     documents = [word for wordlist in documents for word in wordlist]
      9     documents = [i for i in documents if i.isalpha()]
---> 10     wordcloud = WordCloud().generate('testing 123')
     11     plt.figure()
     12     plt.imshow(wordcloud)

~/anaconda3/lib/python3.8/site-packages/wordcloud/wordcloud.py in generate(self, text)
    630         self
    631         """
--> 632         return self.generate_from_text(text)
    633 
    634     def _check_generated(self):

~/anaconda3/lib/python3.8/site-packages/wordcloud/wordcloud.py in generate_from_text(self, text)
    612         """
    613         words = self.process_text(text)
--> 614         self.generate_from_frequencies(words)
    615         return self
    616 

~/anaconda3/lib/python3.8/site-packages/wordcloud/wordcloud.py in generate_from_frequencies(self, frequencies, max_font_size)
    494             while True:
    495                 # try to find a position
--> 496                 font = ImageFont.truetype(self.font_path, font_size)
    497                 # transpose font optionally
    498                 transposed_font = ImageFont.TransposedFont(

~/anaconda3/lib/python3.8/site-packages/PIL/ImageFont.py in truetype(font, size, index, encoding, layout_engine)
    850 
    851     try:
--> 852         return freetype(font)
    853     except OSError:
    854         if not isPath(font):

~/anaconda3/lib/python3.8/site-packages/PIL/ImageFont.py in freetype(font)
    847 
    848     def freetype(font):
--> 849         return FreeTypeFont(font, size, index, encoding, layout_engine)
    850 
    851     try:

~/anaconda3/lib/python3.8/site-packages/PIL/ImageFont.py in __init__(self, font, size, index, encoding, layout_engine)
    171             pass
    172         else:
--> 173             freetype_version = parse_version(features.version_module("freetype2"))
    174             if freetype_version < parse_version("2.8"):
    175                 warnings.warn(

~/anaconda3/lib/python3.8/site-packages/packaging/version.py in parse(version)
     55     """
     56     try:
---> 57         return Version(version)
     58     except InvalidVersion:
     59         return LegacyVersion(version)

~/anaconda3/lib/python3.8/site-packages/packaging/version.py in __init__(self, version)
    294 
    295         # Validate the version and parse it into pieces
--> 296         match = self._regex.search(version)
    297         if not match:
    298             raise InvalidVersion("Invalid version: '{0}'".format(version))

TypeError: expected string or bytes-like object
```
