### ISSUE TITLE
[Question] How to generate a transparent-background image from command line?

### ISSUE THREAD

**Issue by Freed-Wu** [amueller/word_cloud#646]
In python, I know the following code can work:
```python
#! /usr/bin/env python3
from wordcloud import WordCloud
w = WordCloud(background_color=None, mode='RGBA')
w.generate('Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.')
w.to_file('b.png')
```

However, from shell:

```shell
wordcloud_cli --background=None --mode=RGBA > a.png < a.txt
```

```
Traceback (most recent call last):
  File "/usr/bin/wordcloud_cli", line 33, in <module>
    sys.exit(load_entry_point('wordcloud==1.8.1', 'console_scripts', 'wordcloud_cli')())
  File "/usr/lib/python3.9/site-packages/wordcloud/__main__.py", line 33, in main
    wordcloud_cli_main(*wordcloud_cli_parse_args(sys.argv[1:]))
  File "/usr/lib/python3.9/site-packages/wordcloud/wordcloud_cli.py", line 91, in main
    image = wordcloud.to_image()
  File "/usr/lib/python3.9/site-packages/wordcloud/wordcloud.py", line 648, in to_image
    img = Image.new(self.mode, (int(width * self.scale),
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2689, in new
    color = ImageColor.getcolor(color, mode)
  File "/usr/lib/python3.9/site-packages/PIL/ImageColor.py", line 131, in getcolor
    color, alpha = getrgb(color), 255
  File "/usr/lib/python3.9/site-packages/PIL/ImageColor.py", line 116, in getrgb
    raise ValueError(f"unknown color specifier: {repr(color)}")
ValueError: unknown color specifier: 'none'
```

I doubt the color None is converted to 'none' incorrectly. Or any other method to generate a transparent-background image exists?

Thanks.

**Comment by amueller** [comment]
Thank you for the bug report. Yes, it looks like ``None`` is passed as a string instead of as ``None``. I'm not sure where the lower-casing comes from but I think we just need to special case this in the parser.
Are you interested in fixing this?

Cheers
