### ISSUE TITLE
No Development Guide

### ISSUE THREAD

**Issue by JordanTreDaniel** [amueller/word_cloud#672]
#### Description
It is not clear how to begin editing a forked version of this. This may be trivial to a seasoned python dev, but I am not one. My apologies, and thank you for making this available to us.

I know this project has been well though-out, and forked many times. Is there a guide or youtube video for developing your own fork?

#### Steps/Code to Reproduce
1. Forked original project
2. Created a `venv` virtualenv running python 3.8.12
3. Added print statements to `setup.py`, `wordcloud_cli.py`, and `wordcloud.py`, while also editing the code sometimes for a sanity check.
4. Ran `python setup.py develop`
5. Ran `wordcloud_cli --text sza.txt --imagefile wordcloud.jpeg --mask sza.jpeg --repeat` 

#### Expected Results
Expected the print statements to show. Or the edited code to have an effect.

#### Actual Results
 But nothing happens. It's as though it has some saved built version is still running / being compiled. I 

#### Versions
macOS-10.15.7-x86_64-i386-64bit
Python 3.8.12 (default, Oct 13 2021, 06:42:19)
[Clang 12.0.0 (clang-1200.0.32.29)]
NumPy 1.22.3
matplotlib 3.5.1
wordcoud 1.8.1.post9.dev0+g35ce9b7

**Comment by JordanTreDaniel** [comment]
I have managed to affect the code by running `pip install -e .` instead of `python setup.py develop`, however...

1. I am not sure why this helps. 
2. I am still curious to know if there is a guide to editing/forking this project in existence somewhere.

**Comment by jbigdata-git** [comment]
I want to modify src to add feature but I'm facing an issue using the git clone.
My env is ubuntu/python3.8

```
$ git clone https://github.com/amueller/word_cloud.git
$ py3 language_cloud.py
Traceback (most recent call last):
  File "language_cloud.py", line 7, in <module>
    from word_cloud.wordcloud import WordCloud
  File "/home/jb/dev/31-data31tech/word_cloud/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "/home/jb/dev/31-data31tech/word_cloud/wordcloud/wordcloud.py", line 30, in <module>
    from .query_integral_image import query_integral_image
ModuleNotFoundError: No module named 'word_cloud.wordcloud.query_integral_image'

```
Using _**wordcloud**_ from pip install works fine on my env : http://data31tech.com/ai-0.html.
I found posts about this issue, but the work around is to use pip install.

Can someone share a development guide to use git clone in a classic python 3.X env ?

**Comment by amueller** [comment]
``python setup.py develop`` should work, but doesn't add the folder to the PYTHONPATH, which you have to do manually.

Just cloning won't be enough, as you are neither compiling the code (which ``python setup.py develop`` does) nor adding the library to your path (which pip does together with building).

**Comment by jbigdata-git** [comment]
I create 2 directories:
**.../word_cloud/lib**
.**../word_cloud/src** containing the git clone and execute `python3 setup.py develop --install-dir .../word_cloud/lib`.
add `.../word_cloud/lib` to the PYTHONPATH.
use `from word_cloud.src.wordcloud import WordCloud` in my test.

Thanks for fast reply, my env is ready.

**Comment by jbigdata-git** [comment]
The feature I want to add is over: [linked word cloud](http://127.0.0.1/31/images/ai-40.svg).
If interested I can open a pull request.

**Comment by amueller** [comment]
Hey! Sorry I don't see the image you linked. Feel free to open a PR, though I can't tell you if it's in scope before seeing it :)

**Comment by jbigdata-git** [comment]
My bad, it was a localhosted link, I correct the post with a proper link.
If interested tell me the branch I open a PR.
