### ISSUE TITLE
Cannot install wordcloud on OS X 10.7.2

### ISSUE THREAD

**Issue by deepnadevkar** [amueller/word_cloud#72]
Hi there,
I am trying to install word cloud on OSX 10.7.2 and have Anaconda 3, with environments that support python 3.4 and python 2.7. 

I was able to successfully install the requirements after I changed my Anaconda environment to python 2.7. However, when I use Terminal for setup.py I get this error (see below):

Deepna word_cloud-master $ python setup.py install
running install
running build
running build_py
running build_ext
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    package_data={'wordcloud': ['stopwords']}
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/command/install.py", line 539, in run
    self.run_command('build')
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/command/build_ext.py", line 309, in run
    customize_compiler(self.compiler)
  File "/Users/Deepna/anaconda/lib/python3.4/distutils/sysconfig.py", line 182, in customize_compiler
    _osx_support.customize_compiler(_config_vars)
  File "/Users/Deepna/anaconda/lib/python3.4/_osx_support.py", line 418, in customize_compiler
    _find_appropriate_compiler(_config_vars)
  File "/Users/Deepna/anaconda/lib/python3.4/_osx_support.py", line 191, in _find_appropriate_compiler
    "Cannot locate working compiler")
SystemError: Cannot locate working compiler

I also tried to do this instead and got a different error:
Deepna word_cloud-master $ python2.7 setup.py install
running install
running build
running build_py
creating build/lib.macosx-10.6-intel-2.7
error: could not create 'build/lib.macosx-10.6-intel-2.7': Permission denied

Please help! Thanks so much!
Deepna

**Comment by amueller** [comment]
You need to install a c compile like gcc to use wordcloud.

The second error is because you try to install a system package without administrator privileges. Either use sudo (``sudo python2.7 setup.py install`` not really recommended) or install locally ``pip install --user .``

**Comment by deepnadevkar** [comment]
Ah, excellent! That worked. 

One more question: Is there a simple way to override the "merge plurals into a singular count" function? I have some important words like "Rockets" (as in Houston Rockets) that get singularized. 

Thanks so much for your quick response! :)

**Comment by amueller** [comment]
unfortunately not. but the code should be refactored for custom tokenization by passing a callable. I haven't had time for that yet.

**Comment by deepnadevkar** [comment]
sounds good! Thanks so much... this is an awesome tool to have :)
