### ISSUE TITLE
Error in installing library wordcloud

### ISSUE THREAD

**Issue by Xvedk** [amueller/word_cloud#739]
pip install wordcloud
Collecting wordcloud
  Using cached wordcloud-1.9.2.tar.gz (222 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-cwvauk8b\wordcloud_df4464847e954f7d9717d62c80c608ba\setup.py", line 13, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-install-cwvauk8b\wordcloud_df4464847e954f7d9717d62c80c608ba\versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-install-cwvauk8b\wordcloud_df4464847e954f7d9717d62c80c608ba\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-install-cwvauk8b\wordcloud_df4464847e954f7d9717d62c80c608ba\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jpgoldberg** [comment]
It appears that `configparser.SafeConfigParser()` has been long deprecated. It should probably be replaced with `configparser.ConfigParser()` if I am reading issues in other projects correctly (e.g, https://github.com/coin-or/pulp/issues/145 )

**Comment by ilippert** [comment]
Same here, though maybe noteworthy - I only started to have this experience with python3.12

**Comment by ilippert** [comment]
I guess this issue can be closed in favour of https://github.com/amueller/word_cloud/issues/733

**Comment by thomasjpfan** [comment]
This was fixed in 1.9.3. Please try to install wordcloud again and see if it works for you.
