### ISSUE TITLE
How to fix? : python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by amitbang** [amueller/word_cloud#743]
Collecting wordcloud
  Using cached wordcloud-1.9.2.tar.gz (222 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/b2/73_xn1nn4rnffx8w30nx81pm0000gn/T/pip-install-oa0z4_y6/wordcloud_461779112b6f487b80e30a7389ac7272/setup.py", line 13, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/73_xn1nn4rnffx8w30nx81pm0000gn/T/pip-install-oa0z4_y6/wordcloud_461779112b6f487b80e30a7389ac7272/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/b2/73_xn1nn4rnffx8w30nx81pm0000gn/T/pip-install-oa0z4_y6/wordcloud_461779112b6f487b80e30a7389ac7272/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/b2/73_xn1nn4rnffx8w30nx81pm0000gn/T/pip-install-oa0z4_y6/wordcloud_461779112b6f487b80e30a7389ac7272/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by evogelpohl** [comment]
Same: 
Py 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)]
Tried on M2/MB & Win10.current
Cannot get `pip install wordcloud` to work on any machine.

**Comment by thomasjpfan** [comment]
This should be fixed with the 1.9.3 release, which supports Python 3.12. Can you try to install `wordcloud` again and see if it works?

**Comment by evogelpohl** [comment]
> This should be fixed with the 1.9.3 release, which supports Python 3.12. Can you try to install `wordcloud` again and see if it works?

Success. Thanks @thomasjpfan
